name: yuli_my_letters
description: "Hebrew Alphabet Learning App for Yuli - A cute interactive way to learn Hebrew letters."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # SVG Support

  # Local Database

  # Audio Playback
  just_audio: ^0.10.6

  # State Management

  # UI & Animations

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
       - assets/audio/
  

 
dependency_overrides:
  path_provider_android: 2.3.1
  jni_flutter: 1.0.1
  jni: 1.0.0
